<a href="https://colab.research.google.com/github/kimcaprio/nlp_with_tensorflow/blob/master/03_%ED%85%8D%EC%8A%A4%ED%8A%B8_%EC%9C%A0%EC%82%AC%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
#!pip install sklearn

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")

In [5]:
tfidf_vectorizer = TfidfVectorizer()
#tfidf_matrix 에는 embading 된 matrix 데이터가 담겨있음.
tfidf_matrix = tfidf_vectorizer.fit_transform(sent)
#print("tifidf_matrix : ", tifidf_matrix)
#print("tfidf_vectorizer : ", tfidf_vectorizer.)
#tfidf_vectorizer object에 fit_tranform 된 데이터가 존재.
idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니다': 1.0, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


##코사인 유사도

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

print("tfidf_matrix.type : ", type(tfidf_matrix))
print("tfidf_matrix : ", tfidf_matrix)
print("tfidf_matrix[0:1] : ", tfidf_matrix[0:1])
print("tfidf_matrix[1:2] : ", tfidf_matrix[1:2])
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

tfidf_matrix.type :  <class 'scipy.sparse.csr.csr_matrix'>
tfidf_matrix :    (0, 16)	0.23061650387901597
  (0, 7)	0.3241234495558481
  (0, 5)	0.3241234495558481
  (0, 12)	0.3241234495558481
  (0, 8)	0.3241234495558481
  (0, 13)	0.23061650387901597
  (0, 9)	0.3241234495558481
  (0, 1)	0.3241234495558481
  (0, 4)	0.3241234495558481
  (0, 6)	0.3241234495558481
  (0, 11)	0.23061650387901597
  (1, 16)	0.2594822360637418
  (1, 13)	0.2594822360637418
  (1, 11)	0.2594822360637418
  (1, 14)	0.36469322896147516
  (1, 2)	0.36469322896147516
  (1, 0)	0.36469322896147516
  (1, 10)	0.36469322896147516
  (1, 3)	0.36469322896147516
  (1, 15)	0.36469322896147516
tfidf_matrix[0:1] :    (0, 16)	0.23061650387901597
  (0, 7)	0.3241234495558481
  (0, 5)	0.3241234495558481
  (0, 12)	0.3241234495558481
  (0, 8)	0.3241234495558481
  (0, 13)	0.23061650387901597
  (0, 9)	0.3241234495558481
  (0, 1)	0.3241234495558481
  (0, 4)	0.3241234495558481
  (0, 6)	0.3241234495558481
  (0, 11)	0.23061650387901597
tfidf_matr

array([[0.17952266]])

## 유클리디언 유사도


*   n 차원 공간에서 두 점사이의 최단 거리(L2-Distance)구하는 방법.
*   거리가 가까울수록 유사하다는 의미



In [0]:
from sklearn.metrics.pairwise import euclidean_distances

In [8]:
euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.28099753]])

### 다른 유사도와 달리 유사도 값이 1보다 큰 수
- 단순히 두 점사이의 거리를 계산하기 때문에 계속 커질수 있음.
- 0~1 사이의 값을 갖도록 L1 정규화 방법을 이용.(벡터/sum(벡터의 모든값) )

In [0]:
import numpy as np

In [10]:
def l1_normalize(v):
  norm = np.sum(v)
  return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.20491229]])

## 맨하탄 유사도


In [11]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.77865927]])

## 기계 이해



*   기계가 텍스트에 대한 정보 학습 후 질문에 응답하는 문제해결 방법.



## 데이터 이해하기

*   탐색적 데이터 분석 EDA(Exloratory Data Analysis)
*   정해진 틀 없이 주어진 데이터에 대한 정보(평균, 중앙, …) 최대한 많이 뽑아내는 것이 중요

In [12]:
import os
import re

import pandas as pd
import tensorflow as tf
from tensorflow.keras import utils

%cd /content/gdrive/My Drive/CoLab/NLP with Tensorflow/download

data_set = tf.keras.utils.get_file(fname="/content/gdrive/My Drive/CoLab/NLP with Tensorflow/download/imdb.tar.gz",origin="http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz",extract=True)

/content/gdrive/My Drive/CoLab/NLP with Tensorflow/download


In [0]:
def directory_data(directory):
  #print("def directory_data directory : ", directory)
  data = {}
  data["review"] = []
  for file_path in os.listdir(directory):
    with open(os.path.join(directory, file_path), "r") as file:
      data["review"].append(file.read())
  #print("data[] : ", data)
  #print("data[review] : ", data["review"])
  return pd.DataFrame.from_dict(data)

In [0]:
def data(directory):
  #print("def data directory : ", directory)
  pos_df = directory_data(os.path.join(directory, "pos"))
  neg_df = directory_data(os.path.join(directory, "neg"))
  pos_df["sentiment"] = 1
  neg_df["sentiment"] = 0
  
  return pd.concat([pos_df, neg_df])

In [0]:
train_df = data(os.path.join(os.path.dirname(data_set), "aclImdb", "train"))
test_df = data(os.path.join(os.path.dirname(data_set), "aclImdb", "test"))

In [0]:
train_df.head()

In [0]:
reviews = list(train_df['review'])